### ISSUE TITLE
Docker container for GeantV Analysis

### ISSUE THREAD

**Issue by jrmadsen** [Geant-RnD/ExascaleProxyDocuments#3]
- Create a docker container for GeantV with same base image and compilers as Geant4 docker container
- (optionally) Compile with TiMemory extensions that enable process and particle timers

**Comment by jrmadsen** [comment]
@pcanal I think we should add TiMemory into the Geant4 vs. GeantV benchmarks -- I have noticed in some benchmark tests that you report timers to `std::cout` and then grep the log later. I have found this creates a locking at scale when printed out per-event and degrades the MT performance. TiMemory will store all that info in thread-local memory and merge it back into master thread when worker thread is deleted. Then you just report from the master thread at the end of the run. 

If you need variance, min/max, etc. let me know. In some branch I have support for reading other `rusage` types but I have not merged that into the main branch

**Comment by pcanal** [comment]
> some benchmark tests that you report timers to `std::cout` and then grep the log later

In most cases this is 'just' for the overall time (so printing once at the end) and the grep is use to accumulate and average over several runs.

That said, at the time with use gprofile to get the profiling information which is good to look at individual functions and code lines, however, I agree with you that incorporating TiMemory could be beneficial to get something in between (and/or more precise and/or more useable) :)
